# Generated by Django 5.0.2 on 2024-03-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_broker',
            field=models.BooleanField(default=False),
        ),
    ]
