# Generated by Django 5.0.2 on 2024-03-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_broker_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
