# Generated by Django 5.0.2 on 2024-03-03 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0003_remove_propertydealer_email_property_city_and_more'),
        ('tanant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanant',
            name='documents',
        ),
        migrations.AddField(
            model_name='tanant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tanant',
            name='agreement_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_manager.document'),
        ),
        migrations.AddField(
            model_name='tanant',
            name='annual_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanant',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tanant',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tanant',
            name='images',
            field=models.ManyToManyField(to='property_manager.image'),
        ),
        migrations.AddField(
            model_name='tanant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tanant',
            name='lease_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanant',
            name='lease_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='tanant',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanant',
            name='payment_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanant',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_manager.property'),
        ),
        migrations.AddField(
            model_name='tanant',
            name='rent_amount',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanant',
            name='security_deposit',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanant',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tanant',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tanant',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
