# Generated by Django 5.0.2 on 2024-03-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanant', '0002_remove_tanant_documents_tanant_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanant',
            name='contact_number',
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tanant',
            name='name',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
