# Generated by Django 5.0.2 on 2024-03-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanant', '0003_alter_tanant_contact_number_alter_tanant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanant',
            name='email',
        ),
    ]
