# Generated by Django 5.0.2 on 2024-03-04 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanant', '0004_remove_tanant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanant',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanant',
            name='status',
            field=models.CharField(choices=[('ON_RENT', 'On Rent'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
