# Generated by Django 5.0.2 on 2024-03-04 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0005_alter_propertydealer_user'),
        ('tanant', '0005_tanant_created_date_tanant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanant',
            name='agreement_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_agreement_document', to='property_manager.document'),
        ),
        migrations.AlterField(
            model_name='tanant',
            name='images',
            field=models.ManyToManyField(related_name='tenant_images', to='property_manager.image'),
        ),
        migrations.AlterField(
            model_name='tanant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
