# Generated by Django 5.0.2 on 2024-03-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanant', '0008_alter_tanant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanant',
            name='status',
            field=models.CharField(blank=True, choices=[('ON_RENT', 'On Rent'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, null=True),
        ),
    ]
