# Generated by Django 5.0.2 on 2024-03-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanant', '0009_alter_tanant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanantFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tanant_documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('profile', 'Profile'), ('document', 'Document'), ('image', 'Image')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='tanant',
            name='agreement_document',
        ),
        migrations.RemoveField(
            model_name='tanant',
            name='images',
        ),
        migrations.RemoveField(
            model_name='tanant',
            name='logo',
        ),
        migrations.AddField(
            model_name='tanant',
            name='files',
            field=models.ManyToManyField(related_name='tenant_files', to='tanant.tanantfile'),
        ),
    ]
