# Generated by Django 5.0.2 on 2024-03-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_manager', '0001_initial'),
        ('tanant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanant.tanant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rental_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_manager.rentalagreement'),
        ),
    ]
