# Generated by Django 5.0.2 on 2024-03-04 13:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0003_remove_propertydealer_email_property_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalagreement',
            old_name='end_date',
            new_name='lease_end_date',
        ),
        migrations.RenameField(
            model_name='rentalagreement',
            old_name='start_date',
            new_name='lease_start_date',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rentalagreement',
            name='monthly_rent',
        ),
        migrations.AddField(
            model_name='broker',
            name='agreement_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_manager.document'),
        ),
        migrations.AddField(
            model_name='broker',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='images',
            field=models.ManyToManyField(to='property_manager.image'),
        ),
        migrations.AddField(
            model_name='broker',
            name='is_accepting_new_clients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='broker',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broker',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertydealer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_manager.broker'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='broker_commission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='images',
            field=models.ManyToManyField(to='property_manager.image'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='late_payment_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='maintenance_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='monthly_rent_tenant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='renewal_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='security_deposit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='rentalagreement',
            name='agreement_document',
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='agreement_document',
            field=models.ManyToManyField(to='property_manager.document'),
        ),
    ]
