# Generated by Django 5.0.2 on 2024-03-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
        ('property_manager', '0005_alter_propertydealer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='broker.broker'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.broker'),
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
    ]
