# Generated by Django 5.0.2 on 2024-03-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0006_alter_property_broker_alter_rentalagreement_broker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('profile', 'Profile'), ('document', 'Document'), ('image', 'Image')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.AddField(
            model_name='property',
            name='files',
            field=models.ManyToManyField(to='property_manager.propertyfile'),
        ),
    ]
